"""Local question generation and TF-IDF/ML-based answer analysis.

No external service of any kind -- no Ollama server, no cloud AI API, no
network calls, no API keys. Questions come from a curated local question
bank. Answers are scored with a real, if lightweight, NLP/ML technique:
each question has a reference "concept document" built from its expected
keywords, a TF-IDF vectorizer is fit across all of them at import time so
term weighting reflects which concepts are actually distinctive across
the whole question bank (not just this one question), and each answer is
scored by its cosine similarity to its question's reference vector. This
is a genuine vector-space model, not string matching -- it naturally
rewards partial/paraphrased overlap and down-weights generic words that
appear in every reference document, unlike a hardcoded "must contain
this literal keyword" check.

This module has gone through Ollama (local-only), Anthropic (requires
paid credits), and Gemini (free tier, but unstable model availability/
quotas) before landing here: fully local, zero cost, zero external
dependency at runtime, deployable anywhere -- while still doing real
machine learning rather than just keyword substring matching.

Because there's no remote model to call, num_predict/max_tokens-style
knobs, retries, and JSON-repair helpers from the earlier versions are
gone -- there's no malformed or truncated output to repair, since nothing
is being generated by anything other than this file's own code.
"""

import logging
import random
import re

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


def _stem(word):
    """Minimal, dependency-free suffix stripping so that e.g. "decorators"
    and "decorator", or "closures" and "closure", are treated as the same
    term by the vectorizer below. Plain TfidfVectorizer does no stemming
    at all, so without this, a perfectly on-topic answer that happens to
    use the plural/verb form of a reference concept scores zero overlap
    on that term -- this isn't a full linguistic stemmer (that's what a
    library like nltk's PorterStemmer is for), just enough suffix
    handling to catch the common English cases that actually show up in
    short technical answers."""
    if len(word) > 4 and word.endswith("ies"):
        return word[:-3] + "y"
    if len(word) > 4 and word.endswith("es") and word[-3] in "sxz":
        return word[:-2]
    if len(word) > 3 and word.endswith("s") and not word.endswith("ss"):
        word = word[:-1]
    if len(word) > 5 and word.endswith("ing"):
        stem = word[:-3]
        if len(stem) > 2 and stem[-1] == stem[-2] and stem[-1] not in "aeiou":
            stem = stem[:-1]
        return stem
    if len(word) > 4 and word.endswith("ed"):
        stem = word[:-2]
        if len(stem) > 2 and stem[-1] == stem[-2] and stem[-1] not in "aeiou":
            stem = stem[:-1]
        return stem
    return word


_TOKEN_PATTERN = re.compile(r"[a-zA-Z]+(?:-[a-zA-Z]+)?")


def _stemming_tokenizer(text):
    return [_stem(tok.lower()) for tok in _TOKEN_PATTERN.findall(text)]


# sklearn's built-in "english" stop word list is plain, unstemmed text --
# since every vocabulary token here goes through _stem() first, the stop
# words need the same treatment, or common words survive filtering under
# their stemmed form (and sklearn warns about exactly this mismatch).
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS as _RAW_STOP_WORDS  # noqa: E402

_STEMMED_STOP_WORDS = list({_stem(w) for w in _RAW_STOP_WORDS})

log = logging.getLogger("interview_app")

MIN_SCORE = 0
MAX_SCORE = 10
MIN_ANSWER_WORDS = 5

# Below this, an answer is treated as "present but thin" rather than
# "no real answer at all" -- still scored, but the feedback says so.
THIN_ANSWER_WORDS = 25

# Roughly the length of a well-developed answer. Used as the denominator
# for the length component of scoring -- an answer at or above this length
# gets full credit for that component, not just "not too short".
DEVELOPED_ANSWER_WORDS = 60

MAX_HINTS = 3
MAX_STRENGTHS = 4
MAX_SUGGESTIONS = 4


class OllamaError(RuntimeError):
    """Raised on a genuinely invalid usage (e.g. an unknown role/category
    combination not present in the local question bank).

    Kept under its original name (from when this module talked to a
    remote AI service) for compatibility with existing `except
    ai_analyzer.OllamaError` handlers in app.py and interview.py --
    renaming it would mean touching both of those files for no
    functional benefit. In this local, rule-based version it's raised
    far less often, since there's no network/API to fail.
    """


PERSONALITY_GREETINGS = {
    "friendly": "Welcome! I'm excited to learn about your experience. Take your time — this is a safe space to practice.",
    "professional": "Welcome to the interview. I will ask a series of questions. Please provide clear, structured answers.",
    "strict": "Welcome. I expect precise, well-structured answers. Pay attention to detail and cover all aspects of each question.",
}

FILLER_WORDS = [
    "um", "uh", "erm", "hmm", "like", "you know", "sort of", "kind of",
    "basically", "actually", "literally", "i mean", "so yeah", "right",
]


# ============================================================
# Question bank
# ============================================================
# Each entry: (question text, [expected concept keywords]).
# Keywords are simple case-insensitive substrings checked against the
# candidate's answer -- not a claim that these are the *only* correct
# concepts, just the ones this local scorer knows to look for.

_PYTHON_DEVELOPER = {
    "technical": {
        "easy": [
            ("What's the difference between a list and a tuple in Python, and when would you use each?",
             ["mutable", "immutable", "tuple", "list", "hashable", "performance"]),
            ("How do you handle exceptions in Python? When would you use a custom exception class?",
             ["try", "except", "finally", "raise", "custom exception", "inherit"]),
            ("What are Python decorators and how do they work?",
             ["decorator", "wrapper", "function", "higher-order", "closure"]),
        ],
        "medium": [
            ("Explain the difference between a deep copy and a shallow copy in Python.",
             ["shallow copy", "deep copy", "reference", "nested", "copy module", "mutable"]),
            ("What are Python generators and why would you use one instead of a list?",
             ["generator", "yield", "lazy", "memory", "iterator"]),
            ("How does Python's Global Interpreter Lock (GIL) affect multithreaded programs?",
             ["gil", "thread", "cpu-bound", "i/o-bound", "multiprocessing", "concurrency"]),
        ],
        "hard": [
            ("How would you design a Python package to be both installable via pip and testable in CI?",
             ["pyproject.toml", "setup.py", "virtual environment", "pytest", "ci", "packaging", "dependency"]),
            ("Explain how Python's memory management and garbage collection work.",
             ["reference counting", "garbage collector", "cyclic reference", "memory", "weakref"]),
            ("Walk me through how you'd profile and optimize a slow Python function.",
             ["profiler", "cprofile", "bottleneck", "time complexity", "caching", "benchmark"]),
        ],
    },
    "problem-solving": {
        "easy": [("How would you remove duplicate items from a list while preserving order?",
                   ["set", "dictionary", "order", "duplicate", "seen"])],
        "medium": [("How would you find the second-largest number in a list without sorting it?",
                     ["iterate", "compare", "largest", "second largest", "single pass"])],
        "hard": [("How would you design a rate limiter for an API in Python?",
                   ["rate limiter", "token bucket", "sliding window", "timestamp", "queue", "throttle"])],
    },
}

_DATA_SCIENTIST = {
    "technical": {
        "easy": [
            ("What is the difference between supervised and unsupervised learning?",
             ["labeled data", "unlabeled", "supervised", "unsupervised", "classification", "clustering"]),
            ("What's the difference between mean, median, and mode, and when would you prefer one over another?",
             ["mean", "median", "mode", "outlier", "skew", "central tendency"]),
            ("How do you handle missing data in a dataset?",
             ["missing data", "imputation", "drop", "mean", "median", "null"]),
        ],
        "medium": [
            ("Explain the bias-variance tradeoff in machine learning.",
             ["bias", "variance", "overfitting", "underfitting", "tradeoff", "generalization"]),
            ("How would you evaluate a classification model beyond just accuracy?",
             ["precision", "recall", "f1", "confusion matrix", "roc", "auc", "class imbalance"]),
            ("What is regularization and why is it used?",
             ["regularization", "overfitting", "l1", "l2", "lasso", "ridge", "penalty"]),
        ],
        "hard": [
            ("How would you detect and handle data leakage in a machine learning pipeline?",
             ["data leakage", "train test split", "target leakage", "feature engineering", "cross-validation"]),
            ("Explain how gradient boosting works and how it differs from random forests.",
             ["gradient boosting", "random forest", "ensemble", "decision tree", "boosting", "bagging"]),
            ("How would you design an A/B test to measure the impact of a new feature?",
             ["a/b test", "control group", "hypothesis", "sample size", "statistical significance", "p-value"]),
        ],
    },
    "problem-solving": {
        "easy": [("Given a dataset with outliers, how would you decide whether to remove them?",
                   ["outlier", "z-score", "iqr", "domain knowledge", "distribution"])],
        "medium": [("How would you approach building a model to predict customer churn?",
                     ["churn", "features", "labeled data", "classification", "imbalance", "evaluation"])],
        "hard": [("How would you design a recommendation system for an e-commerce platform with limited historical data?",
                   ["cold start", "collaborative filtering", "content-based", "recommendation", "sparse data"])],
    },
}

_WEB_DEVELOPER = {
    "technical": {
        "easy": [
            ("What's the difference between let, const, and var in JavaScript?",
             ["let", "const", "var", "scope", "hoisting", "block scope"]),
            ("What is the box model in CSS?",
             ["box model", "margin", "border", "padding", "content", "box-sizing"]),
            ("What's the difference between GET and POST HTTP methods?",
             ["get", "post", "idempotent", "request body", "query parameter"]),
        ],
        "medium": [
            ("Explain how the JavaScript event loop works.",
             ["event loop", "call stack", "callback queue", "microtask", "asynchronous", "non-blocking"]),
            ("What's the difference between REST and GraphQL?",
             ["rest", "graphql", "endpoint", "over-fetching", "under-fetching", "schema", "query"]),
            ("How do you optimize a website's load performance?",
             ["lazy loading", "caching", "minify", "bundle", "cdn", "compression"]),
        ],
        "hard": [
            ("How would you secure a web application against vulnerabilities like XSS and CSRF?",
             ["xss", "csrf", "sanitize", "csp", "token", "input validation"]),
            ("Explain how you'd design a scalable authentication system across microservices.",
             ["authentication", "jwt", "session", "oauth", "token", "microservices", "single sign-on"]),
            ("How does browser rendering work from receiving HTML to painting the page?",
             ["dom", "cssom", "render tree", "layout", "paint", "reflow", "critical rendering path"]),
        ],
    },
    "problem-solving": {
        "easy": [("How would you implement infinite scroll on a webpage?",
                   ["pagination", "scroll event", "intersection observer", "lazy load", "fetch"])],
        "medium": [("How would you debounce a search input to avoid excessive API calls?",
                     ["debounce", "throttle", "timeout", "api call", "delay"])],
        "hard": [("How would you design a real-time chat feature for a web application?",
                   ["websocket", "real-time", "socket", "message queue", "scalability", "persistence"])],
    },
}

_SOFTWARE_ENGINEER = {
    "technical": {
        "easy": [
            ("What's the difference between an array and a linked list?",
             ["array", "linked list", "contiguous", "pointer", "insertion", "random access"]),
            ("What is Big O notation and why does it matter?",
             ["big o", "time complexity", "space complexity", "worst case", "scalability"]),
            ("What's the difference between a stack and a queue?",
             ["stack", "queue", "lifo", "fifo", "push", "pop", "enqueue"]),
        ],
        "medium": [
            ("Explain the difference between composition and inheritance in object-oriented design.",
             ["composition", "inheritance", "is-a", "has-a", "coupling", "reuse", "polymorphism"]),
            ("What is a race condition and how do you prevent one?",
             ["race condition", "lock", "mutex", "thread safety", "synchronization", "atomic"]),
            ("What design pattern would you use to decouple an object from the classes it depends on?",
             ["design pattern", "dependency injection", "factory", "interface", "decoupling", "abstraction"]),
        ],
        "hard": [
            ("How would you design a system to handle millions of concurrent users?",
             ["horizontal scaling", "load balancer", "caching", "sharding", "microservices", "cdn"]),
            ("Explain the CAP theorem and how it applies to distributed systems.",
             ["cap theorem", "consistency", "availability", "partition tolerance", "distributed", "tradeoff"]),
            ("How would you design a URL shortening service like bit.ly?",
             ["hashing", "unique id", "database", "redirect", "collision", "scalability", "base62"]),
        ],
    },
    "problem-solving": {
        "easy": [("How would you check if two strings are anagrams of each other?",
                   ["anagram", "sort", "character count", "hash map", "compare"])],
        "medium": [("How would you determine if a linked list has a cycle?",
                     ["cycle", "fast pointer", "slow pointer", "floyd", "loop"])],
        "hard": [("How would you design a distributed job scheduler?",
                   ["distributed", "job scheduler", "queue", "worker", "leader election", "fault tolerance", "retry"])],
    },
}

_AI_ENGINEER = {
    "technical": {
        "easy": [
            ("What is the difference between a neural network and a traditional machine learning model?",
             ["neural network", "layers", "non-linear", "feature engineering", "deep learning", "weights"]),
            ("What is an embedding, and why is it useful in NLP?",
             ["embedding", "vector", "semantic", "similarity", "dimensionality", "representation"]),
            ("What is overfitting and how would you detect it?",
             ["overfitting", "validation set", "training accuracy", "generalization", "regularization"]),
        ],
        "medium": [
            ("Explain how attention mechanisms work in transformer models.",
             ["attention", "transformer", "query", "key", "value", "context", "self-attention"]),
            ("What's the difference between fine-tuning and prompt engineering for an LLM?",
             ["fine-tuning", "prompt engineering", "weights", "training", "in-context learning", "parameters"]),
            ("How would you evaluate the quality of an LLM's output?",
             ["evaluation", "human feedback", "benchmark", "hallucination", "relevance", "metrics"]),
        ],
        "hard": [
            ("How would you design a retrieval-augmented generation (RAG) system?",
             ["rag", "vector database", "embedding", "retrieval", "chunking", "context window", "relevance"]),
            ("How would you deploy and monitor a machine learning model in production?",
             ["mlops", "model drift", "monitoring", "deployment", "versioning", "latency", "retraining"]),
            ("How would you reduce hallucinations in a large language model's output?",
             ["hallucination", "grounding", "retrieval", "fact-checking", "prompt", "temperature", "citation"]),
        ],
    },
    "problem-solving": {
        "easy": [("How would you handle an imbalanced dataset when training a classifier?",
                   ["imbalanced", "oversampling", "undersampling", "class weight", "smote", "precision", "recall"])],
        "medium": [("How would you reduce the inference latency of a large model in production?",
                     ["latency", "quantization", "distillation", "batching", "caching", "gpu", "optimization"])],
        "hard": [("How would you design a system to detect when an LLM's response is factually incorrect?",
                   ["fact-checking", "hallucination", "grounding", "retrieval", "verification", "confidence", "citation"])],
    },
}

_DEVOPS_ENGINEER = {
    "technical": {
        "easy": [
            ("What's the difference between a container and a virtual machine?",
             ["container", "virtual machine", "hypervisor", "isolation", "lightweight", "kernel", "image"]),
            ("What is CI/CD and why is it important?",
             ["ci/cd", "continuous integration", "continuous deployment", "pipeline", "automation", "testing"]),
            ("What is the purpose of a Dockerfile?",
             ["dockerfile", "image", "layer", "build", "instructions", "container"]),
        ],
        "medium": [
            ("Explain the difference between horizontal and vertical scaling.",
             ["horizontal scaling", "vertical scaling", "add servers", "add resources", "load balancer", "capacity"]),
            ("What is Infrastructure as Code, and what problem does it solve?",
             ["infrastructure as code", "terraform", "reproducibility", "version control", "automation", "drift"]),
            ("How does Kubernetes handle service discovery and load balancing?",
             ["kubernetes", "service", "pod", "load balancing", "dns", "service discovery", "cluster"]),
        ],
        "hard": [
            ("How would you design a zero-downtime deployment strategy?",
             ["zero-downtime", "blue-green", "canary", "rolling update", "health check", "rollback"]),
            ("How would you set up monitoring and alerting for a production system?",
             ["monitoring", "alerting", "metrics", "logging", "prometheus", "grafana", "threshold", "on-call"]),
            ("How would you secure secrets and credentials in a CI/CD pipeline?",
             ["secrets management", "vault", "environment variable", "encryption", "credentials", "rotation"]),
        ],
    },
    "problem-solving": {
        "easy": [("How would you troubleshoot a service that's returning 500 errors intermittently?",
                   ["logs", "error rate", "monitoring", "reproduce", "rollback", "root cause"])],
        "medium": [("How would you migrate a monolithic application to microservices with minimal downtime?",
                     ["microservices", "monolith", "strangler pattern", "incremental", "downtime", "decouple"])],
        "hard": [("How would you design a disaster recovery plan for a critical production database?",
                   ["disaster recovery", "backup", "replication", "failover", "rto", "rpo", "redundancy"])],
    },
}

QUESTION_BANK = {
    "Python Developer": _PYTHON_DEVELOPER,
    "Data Scientist": _DATA_SCIENTIST,
    "Web Developer": _WEB_DEVELOPER,
    "Software Engineer": _SOFTWARE_ENGINEER,
    "AI Engineer": _AI_ENGINEER,
    "DevOps Engineer": _DEVOPS_ENGINEER,
}

# Behavioral questions are role-agnostic -- the same underlying skills
# (communication, ownership, judgment) apply across every role in the
# bank above, so one shared pool covers all of them.
BEHAVIORAL_QUESTIONS = {
    "easy": [
        ("Tell me about a time you had to learn a new technology quickly for a project.",
         ["learn", "new technology", "deadline", "documentation", "adapt"]),
        ("Describe a time you made a mistake at work. How did you handle it?",
         ["mistake", "responsibility", "fix", "learn", "communicate"]),
        ("Tell me about a project you're proud of and why.",
         ["proud", "impact", "challenge", "contribution", "outcome"]),
        ("How do you prioritize tasks when you have multiple deadlines?",
         ["prioritize", "deadline", "urgent", "important", "communicate"]),
    ],
    "medium": [
        ("Describe a situation where you disagreed with a teammate's technical decision. How did you handle it?",
         ["disagree", "teammate", "communicate", "compromise", "data"]),
        ("Tell me about a time you had to give difficult feedback to a colleague.",
         ["feedback", "difficult", "constructive", "specific", "empathy"]),
        ("Describe a time you had to work with incomplete or unclear requirements.",
         ["unclear requirements", "clarify", "assumption", "stakeholder", "iterate"]),
        ("Tell me about a time you had to balance quality with a tight deadline.",
         ["quality", "deadline", "tradeoff", "scope", "prioritize"]),
    ],
    "hard": [
        ("Tell me about a time you had to make a decision with incomplete information and significant consequences.",
         ["decision", "incomplete information", "risk", "consequence", "judgment"]),
        ("Describe a time you led a project that failed or fell significantly behind. What did you learn?",
         ["failure", "behind schedule", "learn", "root cause", "accountability"]),
        ("Tell me about a time you had to influence a decision without direct authority.",
         ["influence", "authority", "persuade", "stakeholder", "relationship"]),
        ("Describe how you've handled a situation where you strongly disagreed with a team's direction.",
         ["disagree", "direction", "escalate", "professional", "alignment"]),
    ],
}

GENERIC_FALLBACK_HINTS = [
    "Structure your answer with a clear beginning, middle, and end.",
    "Back up your points with a concrete example from experience if you can.",
    "Mention any trade-offs or edge cases relevant to your answer.",
]

# Reverse index: question text -> (keywords, category). Built once at
# import time so generate_hints/analyze_answer can look up a question's
# expected concepts from just the text they're given (interview.py stores
# and passes back question_text, not a reference into the bank itself).
_QUESTION_INDEX = {}

for _role, _categories in QUESTION_BANK.items():
    for _category, _difficulties in _categories.items():
        for _difficulty, _questions in _difficulties.items():
            for _question_text, _keywords in _questions:
                _QUESTION_INDEX[_question_text] = (_keywords, _category)

for _difficulty, _questions in BEHAVIORAL_QUESTIONS.items():
    for _question_text, _keywords in _questions:
        _QUESTION_INDEX[_question_text] = (_keywords, "behavioral")


# ============================================================
# TF-IDF scoring model
# ============================================================
# Each question's expected keywords are turned into a short "reference
# concept document". A single TfidfVectorizer is fit across ALL of these
# reference documents at import time -- fitting on the whole bank rather
# than per-question is what makes the IDF half of TF-IDF meaningful: a
# term that shows up in most questions' references (e.g. common
# engineering words) gets down-weighted, while a term distinctive to one
# specific question's concepts gets weighted more heavily. bigrams are
# included so two-word technical terms ("time complexity", "race
# condition") are captured as a unit, not just their separate words.

_question_texts_ordered = list(_QUESTION_INDEX.keys())
_reference_docs = [
    " ".join(_QUESTION_INDEX[_q][0]) for _q in _question_texts_ordered
]

_VECTORIZER = TfidfVectorizer(
    tokenizer=_stemming_tokenizer,
    token_pattern=None,
    ngram_range=(1, 2),
    stop_words=_STEMMED_STOP_WORDS,
)
_REFERENCE_MATRIX = _VECTORIZER.fit_transform(_reference_docs)

# question text -> row index into _REFERENCE_MATRIX, so analyze_answer
# can grab the right reference vector for whichever question it's scoring.
_QUESTION_ROW = {
    _q: _i for _i, _q in enumerate(_question_texts_ordered)
}


# ============================================================
# Public API (same signatures the previous LLM-backed versions used)
# ============================================================

def warm_up():
    """The TF-IDF vectorizer is already fit at import time (see the
    module-level _VECTORIZER/_REFERENCE_MATRIX setup above) -- there's no
    lazy loading or external service to warm up here. This just confirms
    it's ready and logs the vocabulary size, so app.py's startup call
    (and the /api/warmup endpoint) still do something meaningful to check."""
    log.info(
        "Local TF-IDF scoring model ready -- %d questions, %d-term "
        "vocabulary.", len(_QUESTION_INDEX), len(_VECTORIZER.vocabulary_),
    )


def generate_question(role, difficulty, category, personality, previous_questions, topics=None):
    """Pick a question from the local bank for this role/category/
    difficulty that hasn't already been asked this session, if possible."""

    if category == "behavioral":
        pool = BEHAVIORAL_QUESTIONS.get(difficulty, [])
    else:
        role_bank = QUESTION_BANK.get(role)
        if role_bank is None:
            log.warning("Unknown role %r, falling back to behavioral pool", role)
            pool = BEHAVIORAL_QUESTIONS.get(difficulty, [])
        else:
            pool = role_bank.get(category, {}).get(difficulty, [])

    if not pool:
        # Shouldn't happen with the roles/categories/difficulties this
        # app actually offers, but degrade gracefully rather than crash
        # a live session if it ever does.
        log.error(
            "No questions available for role=%s category=%s difficulty=%s",
            role, category, difficulty,
        )
        return "Tell me about a project you've worked on recently."

    asked = set(previous_questions or [])
    unused = [(q, kw) for q, kw in pool if q not in asked]

    question_text, _keywords = random.choice(unused) if unused else random.choice(pool)

    log.info(
        "Selected %s question: role=%s difficulty=%s category=%s",
        "unused" if unused else "repeat (pool exhausted)",
        role, difficulty, category,
    )
    return question_text


def generate_hints(role, question_text, difficulty):
    """Structural hints (always shown) plus one topic nudge pulled from
    the question's expected concepts, if the question is recognized."""

    hints = list(GENERIC_FALLBACK_HINTS)

    entry = _QUESTION_INDEX.get(question_text)
    if entry:
        keywords, _category = entry
        if keywords:
            topic = random.choice(keywords)
            hints.append(f"Consider how \"{topic}\" relates to your answer.")

    return hints[:MAX_HINTS]


def _score_answer(question_text, answer, keywords):
    """Score 0-10 from two signals: TF-IDF cosine similarity between the
    answer and the question's reference concept vector (the real ML
    component -- a continuous, term-weighted similarity, not a binary
    keyword check), and how developed (not just long) the answer is.

    Also returns matched/missing keyword lists -- these are a separate,
    literal substring check used only to generate readable strengths/
    suggestions text ("you mentioned X", "you didn't mention Y"), since
    a cosine similarity score alone can't be turned into that kind of
    concrete, human-readable feedback. The score itself comes from the
    similarity, not from this list."""

    row = _QUESTION_ROW.get(question_text)
    if row is not None:
        answer_vector = _VECTORIZER.transform([answer])
        similarity = float(cosine_similarity(answer_vector, _REFERENCE_MATRIX[row])[0, 0])
    else:
        # Question not in the bank (see analyze_answer's fallback path) --
        # shouldn't reach here in practice since that path returns early,
        # but fall back to a neutral similarity rather than crash.
        similarity = 0.5

    lowered = answer.lower()
    matched = [kw for kw in keywords if kw.lower() in lowered]
    missing = [kw for kw in keywords if kw not in matched]

    word_count = len(re.findall(r"[A-Za-z0-9']+", answer))
    length_component = min(1.0, word_count / DEVELOPED_ANSWER_WORDS)

    # The length bonus is GATED by similarity (multiplicative, not
    # additive) rather than length being an independent point source --
    # a purely additive formula lets any sufficiently long answer earn
    # up to 3 points regardless of topic, which let a long, completely
    # off-topic answer outscore a short but genuinely on-topic one in
    # testing. Scaling the length bonus by similarity means development
    # only pays off once the answer is actually about the right thing.
    raw = similarity * (7 + length_component * 3)
    score = max(MIN_SCORE, min(MAX_SCORE, round(raw)))

    return score, matched, missing


_STRENGTH_TEMPLATES = {
    "friendly": "Nice, you touched on {kw} — that's an important part of this.",
    "professional": "The answer appropriately addressed {kw}.",
    "strict": "The mention of {kw} was correctly identified as relevant.",
}
_SUGGESTION_TEMPLATES = {
    "friendly": "It'd be even stronger if you also mentioned {kw}.",
    "professional": "Consider addressing {kw} for a more complete answer.",
    "strict": "Discussion of {kw} was expected and should have been addressed.",
}
_GENERIC_STRENGTHS = {
    "friendly": "You engaged directly with the question, which is a great start.",
    "professional": "The answer addressed the core of what the question asked.",
    "strict": "The answer attempted to engage with the question directly.",
}
_GENERIC_SUGGESTIONS = {
    "friendly": "Try adding a bit more detail or a concrete example next time.",
    "professional": "Add more detail and structure to fully answer the question.",
    "strict": "The answer lacked sufficient depth and concrete detail.",
}


def analyze_answer(role, question, answer, personality):
    word_count = len(re.findall(r"[A-Za-z0-9']+", answer))

    if word_count < MIN_ANSWER_WORDS:
        log.info(
            "Answer too short (%d words, need %d) for: %s",
            word_count, MIN_ANSWER_WORDS, question[:80],
        )
        return {
            "score": MIN_SCORE,
            "strengths": [],
            "suggestions": [
                "This answer is too short to evaluate -- please write a "
                "complete response that directly addresses the question."
            ],
            "improved_answer": "",
        }

    entry = _QUESTION_INDEX.get(question)
    if entry is None:
        # Question text wasn't recognized (e.g. saved from a previous
        # LLM-generated session, before this local version existed) --
        # fall back to a length-only assessment rather than failing.
        log.warning(
            "Question not found in local bank, scoring on length only: %s",
            question[:80],
        )
        length_component = min(1.0, word_count / DEVELOPED_ANSWER_WORDS)
        score = max(MIN_SCORE, min(MAX_SCORE, round(length_component * 10)))
        matched, missing = [], []
    else:
        keywords, _category = entry
        score, matched, missing = _score_answer(question, answer, keywords)

    strength_template = _STRENGTH_TEMPLATES.get(personality, _STRENGTH_TEMPLATES["professional"])
    suggestion_template = _SUGGESTION_TEMPLATES.get(personality, _SUGGESTION_TEMPLATES["professional"])

    strengths = [strength_template.format(kw=kw) for kw in matched[:MAX_STRENGTHS]]
    suggestions = [suggestion_template.format(kw=kw) for kw in missing[:MAX_SUGGESTIONS]]

    if not strengths:
        strengths = [_GENERIC_STRENGTHS.get(personality, _GENERIC_STRENGTHS["professional"])]
    if not suggestions:
        suggestions = [_GENERIC_SUGGESTIONS.get(personality, _GENERIC_SUGGESTIONS["professional"])]

    if missing:
        improved_answer = (
            "A stronger answer would also cover: " + ", ".join(missing[:MAX_SUGGESTIONS])
            + ". Try naming these explicitly and explaining how each one applies here."
        )
    elif word_count < THIN_ANSWER_WORDS:
        improved_answer = (
            "The right ideas are here -- develop them further with a concrete "
            "example or a brief explanation of trade-offs to make the answer "
            "more complete."
        )
    else:
        improved_answer = ""

    log.info("Answer scored %d/10 (%d/%d concepts matched)",
             score, len(matched), len(matched) + len(missing))

    return {
        "score": score,
        "strengths": strengths,
        "suggestions": suggestions,
        "improved_answer": improved_answer,
    }


_SUMMARY_TIERS = [
    (8, "an excellent overall performance"),
    (6, "a solid performance with room to grow"),
    (4, "a mixed performance"),
    (0, "an early-stage performance that would benefit from more practice"),
]


def generate_final_summary(role, personality, difficulty, average_score, answers):
    tier = next(label for threshold, label in _SUMMARY_TIERS if average_score >= threshold)

    scored = [a for a in (answers or []) if isinstance(a.get("score"), (int, float))]
    best = max(scored, key=lambda a: a["score"], default=None)
    worst = min(scored, key=lambda a: a["score"], default=None)

    sentences = [
        f"This {difficulty}-difficulty {role} interview showed {tier}, "
        f"averaging {average_score:.1f}/10 across {len(answers or [])} question(s)."
    ]

    if best is not None and best is not worst:
        sentences.append(
            f"The strongest response was to \"{best['question_text']}\", "
            f"scoring {best['score']}/10."
        )

    if worst is not None and worst is not best:
        sentences.append(
            f"The area with the most room to improve was the response to "
            f"\"{worst['question_text']}\" ({worst['score']}/10) -- "
            "revisiting that topic would be a good next step."
        )

    if average_score >= 7:
        sentences.append(
            "Overall, keep practicing to maintain this level under "
            "different question styles and difficulty tiers."
        )
    else:
        sentences.append(
            "Focus on naming specific concepts and trade-offs directly in "
            "your answers, rather than describing them only in general terms."
        )

    summary = " ".join(sentences)
    log.info("Generated final summary: role=%s avg_score=%.1f", role, average_score)
    return summary


def count_filler_words(text):
    """Return the total filler-word count and which ones occurred, used as a
    communication-quality signal alongside the content-coverage score."""
    lowered = text.lower()
    matched = []
    total = 0
    for phrase in FILLER_WORDS:
        count = len(re.findall(r"\b" + re.escape(phrase) + r"\b", lowered))
        if count:
            matched.append({"phrase": phrase, "count": count})
            total += count
    return total, matched
